# AWSTemplateFormatVersion: "2010-09-09"
# Description: "Cloudwatch Event template"
Resources:
  CostReporterEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: "Cloudwatch event for invocation of CostReporter Lambda"
      Name: "AwsCostReportEvent-${self:custom.stage}"
      ScheduleExpression: "cron(0 0 ? * SUN *)"
      State: "ENABLED"
      Targets:
        - Arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:aws-cost-repoter-${self:custom.stage}-costReporter
          Id: CostReporterEventTargetId-${self:custom.stage}

  CostReporterLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: aws-cost-repoter-${self:custom.stage}-costReporter
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CostReporterEvent.Arn
