# AWSTemplateFormatVersion: "2010-09-09"
# Description: "IAM Role template"
Resources:
  CostReporterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "CostReporterLambdaRole-${self:custom.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "CostReporterLambdaPolicy-${self:custom.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ce:DescribeReport
                  - ce:DescribeCostCategoryDefinition
                  - ce:ListCostCategoryDefinitions
                  - ce:GetCostCategories
                  - ce:GetCostAndUsage
                  - ce:GetDimensionValues
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:publish
                Resource: "arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:CostReporterSnsTopic-${self:custom.stage}"
      Tags:
        - Key: "AppName"
          Value: "ConstReporter"
