# AWSTemplateFormatVersion: "2010-09-09"
# Description: "IAM Role template"
Resources:
  CostReporterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "CostReporterLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "CostReporterLambdaRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ce:DescribeReport
                  - ce:DescribeCostCategoryDefinition
                  - ce:ListCostCategoryDefinitions
                  - ce:GetCostCategories
                Resource: "*"
      Tags:
        -
          Key: "AppName"
          Value: "ConstReporter"

